DEFAULT_PARA = {
    "plot": False,
    "lambda_0": 1.326e-6,
    "FWHM": 0.0833e-6,
    "alpha": 0.02,
    "penalty": [[0.01, 10e-9]],
    "SOURCE_typ": "gaussian_released",
    "NL": 2,
    "NH": 3,
    "N": 14,
    "MIN_FEATURE_SIZE": 50.0,
    "FOM_typ": "square",
    "grating_typ": "subw_grating",
    "paras_init": None,
    "maxiter": 90,
    "logger": None,
    "start_radius": 10e-6,
    "taper_angle": 24,
}
